#\u903B\u8F91\u5220\u9664\u503C
# \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
mybatis-plus.global-config.db-config.logic-delete-value=id%127+1
# \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
mybatis-plus.global-config.db-config.logic-not-delete-value=0
# mp\u9ED8\u8BA4\u914D\u7F6E\u6587\u4EF6
mybatis-plus.config-location=classpath:mybatis-config.xml
